export * from "./Table";

export const PACKAGES = [
  {
    id: 1,
    title: "",
    stylesTitle: "table__title-none",
    price: "Soluciones",
    subtitle: "El valor de los planes incluyen IVA",
    serveillance: "Vigilancia Juadicial judicial",
    alert: "Alerta de procesos",
    attendance: "Asistencia legal",
    authorizations: "Autorización de documentos",
    user: "Usuarios",
    storage: "Almacenamiento en la nube",
  },
  {
    id: 2,
    title: "Plan demo",
    stylesTitle: "table__title-purple",
    price: "0.00",
    subtitle: "0.00 COP anual",
    serveillance: "1 vigilancia",
    alert: " 1 alerta para 1 proceso",
    attendance: "1 hora de asistencia",
    authorizations: "1 automatizacion",
    user: " 1 usuario",
    storage: "5GB",
  },
  {
    id: 3,
    title: "Plan estandar",
    stylesTitle: "table__title-purple",
    price: "190.000",
    subtitle: "2'280.000 COP anual",
    serveillance: "10 vigilancia",
    attendance: "4 horas de asistencia",
    alert: " 10 alertas",
    authorizations: "10 automatizacion",
    user: " 2 usuario",
    storage: "100GB",
  },
  {
    id: 4,
    title: "Plan plus",
    stylesTitle: "table__title-green",
    price: "426.166",
    subtitle: "5'090.000 COP anual",
    serveillance: "1/30 vigilancias dispanibles",
    alert: "29/30 alertas disponibles",
    attendance: "8.5/10 horas de asistencia",
    authorizations: "30 autorización",
    user: " 1 usuario",
    storage: "0./200 GB en uso",
  },
  {
    id: 5,
    title: "Plan premium",
    stylesTitle: "table__title-blue",
    price: "620.000",
    subtitle: "9'980.000",
    attendance: "20 horas de asistencia",
    serveillance: "80 vigilancias",
    alert: " 80 alertas",
    authorizations: "50 automatizaciones",
    user: " 10 usuario",
    storage: "500 GB",
  },
];
